### PR TITLE
Update SQLite to 3.42.0

### PR DESCRIPTION
**Pull request by theraphim**
This release adds a bunch of API features which may be of use later, such as value encoding. However we are most interested in SQL-level improvements and bugfixes.

### CODE REVIEW

**Comment by theraphim** [comment]
Greetings!

Is there anything I can do to help getting this merged?

Thanks!

**Comment by theraphim** [comment]
I have updated this PR to the latest sqlite release.

**Comment by anacrolix** [comment]
https://github.com/crawshaw/sqlite/issues/123#issuecomment-1430240191

**Comment by anacrolix** [comment]
@theraphim I've merged this in a fork that I've started: https://github.com/go-llsqlite/llsqlite/commit/c3a07ef108f7d226d61bb1397dd4bfaa56b2430d.

**Comment by theraphim** [comment]
> @theraphim I've merged this in a fork that I've started: [go-llsqlite/llsqlite@c3a07ef](https://github.com/go-llsqlite/llsqlite/commit/c3a07ef108f7d226d61bb1397dd4bfaa56b2430d).

Thanks! I'm switching all my toys to your fork :)

**Pull request closed without merging**
