### PR TITLE
sqlite: document 1-based parameter indices in more places

### PR DESCRIPTION
**Pull request by josharian**

### CODE REVIEW

**Comment by AdamSLevy** [comment]
Please add empty lines so that go doc formats the documentation better.

For example, currently it formats as such:
```
$ go doc BindInt64
package sqlite // import "crawshaw.io/sqlite"

func (stmt *Stmt) BindInt64(param int, value int64)
    BindInt64 binds value to a numbered stmt parameter. Parameter indices start
    at 1. https://www.sqlite.org/c3ref/bind_blob.html

```

But it should be like this:
```
$ go doc BindInt64
package sqlite // import "crawshaw.io/sqlite"

func (stmt *Stmt) BindInt64(param int, value int64)
    BindInt64 binds value to a numbered stmt parameter.

    Parameter indices start at 1.

    https://www.sqlite.org/c3ref/bind_blob.html

```

**Comment by josharian** [comment]
Done

**Comment by AdamSLevy** [comment]
not quite. run go doc to see what I'm talking about. put the url on its own line.

**Comment by josharian** [comment]
ah. I foolishly assumed that the existing ones were ok. i'll fix them all.

**Comment by AdamSLevy** [comment]
Oh were there ones like that before? Appreciate you cleaning that up. It'll read much cleaner in go doc both on the CLI and on the web.

**Comment by josharian** [comment]
take three :)

**Pull request merged**
